sudo: required
services:
  - docker
before_install:
  - docker build -t react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true react-app npm run test
language: generic
edge: true
deploy:
  provider: "elasticbeanstalk"
  region: "ap-southeast-1"
  app: "docker-react"
  environment: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-307882631086"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY